name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install zsh and gawk
        run: |
          sudo apt-get update
          sudo apt-get install -y zsh gawk
      - name: Run tests
        run: |
          zsh tests/test_trim.sh